### PR TITLE
Conference view pages 

### LINKED ISSUE #14: Add conference view page

### PR DESCRIPTION
**Pull request by hola-soy-milk**
Closes #14 

image

image

Not super excited about it being a link in the dropdown... do we wanna have an index page of confs?

### CODE REVIEW

**Comment by SaraVieira** [comment]
Why not link it from the conference name?

**Comment by SaraVieira** [comment]
Yeah! Sounds good!

**Comment by hola-soy-milk** [comment]
Perfect, ty! Ready for review 😌

**Review by SaraVieira — APPROVED** [review]

**Comment by SaraVieira** [comment]
Nice! Thank you for all the components!!

**Pull request merged**
